### ISSUE TITLE
all item of dropdown with bulma theme is active when one is clicked

### ISSUE THREAD

**Issue by flim** [oruga-ui/oruga#601] opened 2023-09-24 13:18 UTC
### Overview of the problem

**Oruga** version: 0.6.0
**Vuejs** version: 3.3.4
**oruga-ui/theme-bulma** version 0.2.11

**OS/Browser**: Chrome

### Description

With a basic dropdown with many items. When an item is clicked, all the items became active with the class "is-active" and all have a "is-active" background.

### Steps to reproduce

the first [base example](https://oruga.io/components/Dropdown.html#examples) from the documentation: 

```html
<o-dropdown aria-role="list">
        <template #trigger="{ active }">
            <o-button
                variant="primary"
                label="Click me!"
                :icon-right="active ? 'caret-up' : 'caret-down'" />
        </template>

        <o-dropdown-item aria-role="listitem" label="Action" />
        <o-dropdown-item aria-role="listitem" label="Another action" />
        <o-dropdown-item aria-role="listitem" label="Something else" />
    </o-dropdown>
```

Then click on one item.

### Expected behavior

Only the selected item should have the class "is-active".

### Actual behavior

All items of the dropdown have the class "is-active".

https://github.com/oruga-ui/oruga/assets/811184/8e3b7d62-d5bd-453e-a207-7ea673caac32

**Comment by mlmoravek** [comment] 2023-10-15 19:16
Seems duplicate of #378

**Closed** 2023-10-15 19:16 UTC
